name: Release to Mac App Store (CD)

on:
  repository_dispatch:
    types: [release-mac]
    inputs:
      ref:
        required: true
      packageInitialism:
        required: true

jobs:
  releaseToMacAppStore:
    name: Release to the Mac App Store
    runs-on: macos-latest
    env:
      APPLE_CONNECT_EMAIL: ${{ secrets.APPLE_CONNECT_EMAIL }}
      APPLE_DEVELOPER_EMAIL: ${{ secrets.APPLE_DEVELOPER_EMAIL }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_TEAM_NAME: ${{ secrets.APPLE_TEAM_NAME }}
      MAC_APPLICATION_CERTIFICATE: ${{ secrets.MAC_APPLICATION_CERTIFICATE }}
      MAC_APPLICATION_PASSWORD: ${{ secrets.MAC_APPLICATION_PASSWORD }}
      MAC_INSTALLER_CERTIFICATE: ${{ secrets.MAC_INSTALLER_CERTIFICATE }}
      MAC_INSTALLER_PASSWORD: ${{ secrets.MAC_INSTALLER_PASSWORD }}
      APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
      APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
      APPSTORE_P8: ${{ secrets. APPSTORE_P8 }}
      APPSTORE_P8_PATH: ${{ format('{0}/fastlane/p8.json', github.workspace) }}
      MAC_APP_ID: com.finoldigital.CardGameSimulator
      MAC_BUILD_PATH: ${{ format('{0}/build/StandaloneOSX', github.workspace) }}
      PROJECT_NAME: Card Game Simulator
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.events.inputs.ref }}
      - name: Download StandaloneOSX Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.inputs.packageInitialism }}-StandaloneOSX
          path: build/StandaloneOSX
      - name: Write to Changelog
        env:
          RELEASE_NOTES: ${{ github.event.release.body }}
        run: echo "$RELEASE_NOTES" > fastlane/metadata/android/en-US/changelogs/default.txt
      - name: Install Fastlane
        run: bundle install
      - name: Fix version for StandaloneOSX
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'fixversion'
      - name: Fix File Permissions, Code-Sign, and Get Release Notes
        id: terminal
        run: |
          find $MAC_BUILD_PATH -type f -name "**.sh" -exec chmod +x {} \;
          chmod +x fastlane/sign-osx-build.sh
          ./fastlane/sign-osx-build.sh
          echo "$APPSTORE_P8" > $APPSTORE_P8_PATH
          export notes="$(cat fastlane/metadata/android/en-US/changelogs/default.txt)"
          notes="${notes//'%'/%25}"
          notes="${notes//$'\n'/%0A}"
          notes="${notes//$'\r'/%0D}"
          echo "$notes"
          echo "::set-output name=RELEASE_NOTES::$notes"
      - name: Upload to the Mac App Store
        uses: maierj/fastlane-action@v2.0.1
        env:
          RELEASE_NOTES: ${{ steps.terminal.outputs.RELEASE_NOTES }}
        with:
          lane: 'mac macupload'