name: Release to Google Play (CD)

on:
  repository_dispatch:
    types: [release-google-play]
    inputs:
      ref:
        required: true
      packageInitialism:
        required: true
      packageName:
        required: true
      packageNameLower:
        required: true
      packageNameSpaced:
        required: true

jobs:
  releaseToGooglePlay:
    name: Release to the Google Play Store
    runs-on: ubuntu-latest
    env:
      GOOGLE_PLAY_KEY_FILE: ${{ secrets.GOOGLE_PLAY_KEY_FILE }}
      GOOGLE_PLAY_KEY_FILE_PATH: ${{ format('{0}/fastlane/api-nyarenari.json', github.workspace) }}
      ANDROID_BUILD_FILE_PATH: ${{ format('{0}/build/Android/Android.aab', github.workspace) }}
      ANDROID_PACKAGE_NAME: com.nyarenari.${{ github.event.inputs.packageNameLower }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.packageInitialism }}
      - name: Download Android Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.inputs.packageInitialism }}-Android
          path: build/Android
      - name: Write to Changelog
        env:
          RELEASE_NOTES: ${{ github.event.release.body }}
        run: echo "$RELEASE_NOTES" > fastlane/metadata/android/en-US/changelogs/default.txt
      - name: Add Authentication
        run: echo "$GOOGLE_PLAY_KEY_FILE" > $GOOGLE_PLAY_KEY_FILE_PATH
      - name: Install Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Upload to Google Play
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'android playprod'
